# 自定义层
---

## 构造一个没有任何参数的自定义层

In [2]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()
    
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

## 将层作为组件合并到构建更复杂的模型中

In [8]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(6.9849e-09, grad_fn=<MeanBackward0>)

## 带参数的图层

In [12]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))#逗号说明是向量
        
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[-1.4965e-03,  1.6082e+00, -7.9093e-01],
        [ 3.4568e-01,  4.2131e-01,  4.3902e-02],
        [ 2.2800e-01, -4.7235e-01, -5.4972e-01],
        [ 3.2476e-01, -1.3291e+00, -4.8913e-01],
        [ 1.1215e+00,  4.2105e-01, -6.0219e-01]], requires_grad=True)

## 使用自定义层直接执行正向传播计算

In [13]:
dense(torch.rand(2,5))

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.6480, 0.0000]])

## 使用自定义层构建模型


In [22]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[ 6.7472],
        [15.8569]])