In [1]:
import torch

X = torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[1.0,2,3,4],[5,6,7,8],[9,10,11,13]])

# print(torch.cat((X,Y),dim = 0))
# print(torch.cat((X,Y),dim = 1))
print(Y)
print(Y.sum())

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 13.]])
tensor(79.)


In [2]:
#广播机制

a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
c = torch.tensor([[0,0],[1,1],[2,2]])
d = torch.tensor([[0,1],[0,1],[0,1]])
print(a)
print(b)
print(a+b)
print(c+d)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [3]:
e = a+b

e[0:2,:] = 12
print(e)

tensor([[12, 12],
        [12, 12],
        [ 2,  3]])


In [4]:
X = torch.arange(4).reshape(2,2)
Y = torch.zeros_like(X)  #创建与X同型的0矩阵
print(X,Y)


tensor([[0, 1],
        [2, 3]]) tensor([[0, 0],
        [0, 0]])


In [5]:
A = X.numpy()
B = torch.tensor(A)
A = torch.tensor([2.5])
a = A.item()
# print(type(A))
# print(type(B))
print(a)

2.5


In [6]:
#写数据
import os
#写到这里了C:\Users\ThinkPad\data

os.makedirs(os.path.join('.','data'),exist_ok=True)
data_file = os.path.join('.','data','house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127\n')
    f.write('2,NA,106\n')
    f.write('4,NA,178\n')
    f.write('NA,NA,140\n')

In [7]:
#!pip install pandas -i https://pypi.tuna.tsinghua.edu.cn/simple

import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms Alley  Price
0       NaN  Pave    127
1       2.0   NaN    106
2       4.0   NaN    178
3       NaN   NaN    140

In [20]:
#对于数值部分的填充
#在data中通过位置索引iloc,将data分为inputs[data 的0和1列], 
#outputs[data的最后一列].

inputs, outputs = data.iloc[:, 0:2], data.iloc[:,2]
inputs = inputs.fillna(inputs.mean())
inputs,outputs

(   NumRooms Alley
 0       3.0  Pave
 1       2.0   NaN
 2       4.0   NaN
 3       3.0   NaN,
 0    127
 1    106
 2    178
 3    140
 Name: Price, dtype: int64)

In [30]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs = inputs.astype(float)

In [31]:
import torch

X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127, 106, 178, 140]))

In [32]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y, x * y, x/y, x**2.0

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [35]:
x = torch.arange(4)
len(x)
x.shape

torch.Size([4])

In [37]:
A = torch.arange(20).reshape(5, 4)
print(A)
print(A.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [40]:
B = torch.tensor([[1, 2, 3],[2, 0, 4],[3, 4, 5]])
B == B.T


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [41]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [44]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() #通过分配新内存，将A的一个副本分配给B
A, A + B,A * B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

In [47]:
a = 2
x = torch.arange(24).reshape(2,3,4)
print(a + x)
print(a * x)

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])


In [48]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [50]:
#汇集所有行的元素，拍扁
A = torch.arange(12).reshape(3,4)
A_sum_axis0 = A.sum(axis=0)
A, A_sum_axis0, A_sum_axis0.shape

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([12, 15, 18, 21]),
 torch.Size([4]))

In [51]:
#汇集所有列的元素，拍墙上

A_sum_axis1 = A.sum(axis=1)
A, A_sum_axis1, A_sum_axis1.shape

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([ 6, 22, 38]),
 torch.Size([3]))

In [56]:
A = torch.arange(12, dtype=torch.float32).reshape(3,4)
A.mean(), A.numel(), A.sum() / A.numel()

(tensor(5.5000), 12, tensor(5.5000))

In [57]:
A, A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([4., 5., 6., 7.]),
 tensor([4., 5., 6., 7.]))

In [61]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895]])

In [62]:
#累加求和
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.]])

In [64]:
x = torch.arange(4,dtype=torch.float32)
y = torch.ones(4,dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [66]:
A, x, A.shape, x.shape, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([3, 4]),
 torch.Size([4]),
 tensor([14., 38., 62.]))

In [67]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.]])

In [69]:
#L2范数是向量元素平方和的根


u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [70]:
#L1范数就是向量元素绝对值的和
torch.abs(u).sum()


tensor(7.)

In [74]:
#矩阵的弗罗贝尼乌斯范数（Frobenius norm)是矩阵元素的平方和的平方根
torch.norm(torch.ones((4, 9)))

tensor(6.)

In [77]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [91]:
import torch

x = torch.arange(4.0)
x.requires_grad = True
#等价于 x =  torch.arange(4.0,requires_grad=True)
x.grad  #默认值是None

y = 2 * torch.dot(x, x)  #y = 2x^2
y.backward()  #求导
x.grad == 4*x

tensor([True, True, True, True])

In [95]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [96]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [105]:
x.grad.zero_()
y = x * x
u = y.detach()  #y不再是关于x的函数
z = u * x

z.sum().backward()
x, x.grad 

(tensor([0., 1., 2., 3.], requires_grad=True), tensor([0., 1., 4., 9.]))

In [102]:
x.grad.zero_()
y.sum().backward()
x.grad == 2*x

tensor([True, True, True, True])

In [162]:
import matplotlib.pyplot as plt

def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
        print(b)
    if b.sum() > 0:
        print(b.sum())
        c = b
    else:
        c = 100 * b
    return c

#a = torch.linspace(-10, 10, 10)
a = torch.randn(size=(), requires_grad=True)
#a = torch.tensor([3.0])
d = f(a)
# a = a.detach().numpy()
# d = d.detach().numpy()
print(d)
d.backward()

# plt.figure(1, figsize=(8, 6))
# plt.plot(a, d, c='red', label='f(a)') #输入，输出，颜色，标签
# plt.xlim((-100000, 1000000))  #设置y的值域
# plt.ylim((-100000, 1000000))  #设置y的值域
# plt.legend(loc='best',edgecolor='blue') #设置图例 以及图例边框

a.grad == d / a

tensor(8.5131, grad_fn=<MulBackward0>)
tensor(17.0262, grad_fn=<MulBackward0>)
tensor(34.0524, grad_fn=<MulBackward0>)
tensor(68.1048, grad_fn=<MulBackward0>)
tensor(136.2095, grad_fn=<MulBackward0>)
tensor(272.4190, grad_fn=<MulBackward0>)
tensor(544.8380, grad_fn=<MulBackward0>)
tensor(1089.6760, grad_fn=<MulBackward0>)
tensor(1089.6760, grad_fn=<SumBackward0>)
tensor(1089.6760, grad_fn=<MulBackward0>)


tensor(True)